baseURL: ""
languageCode: en-us
title: Information Security
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Welcome to my Blog about Information Security"
    Content: "This site covers important topics related to Information Security such as Spam and Phishing attacks. 
    The intent is to raise general awareness to better inform people about the risks related to such information security incidents."


  showReadingTime: true
  showBreadCrumbs: true
